apiVersion: v1
kind: Service
metadata:
  name: student-frontend-service
spec:
  selector:
    app: student-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
